### ISSUE TITLE
The disappearance of the collision of the world

### ISSUE THREAD

**Issue by AndreyFant** [multitheftauto/mtasa-blue#1948]
**Describe the bug**
If on one server the collision of the world is replaced with another, then if you do not close the mta, re-enter another server, then there this colony will be the same as on the previous server

**To reproduce**
1.Open mta
2.Log in to the server with the land colision replaced with an empty one
3.Log out of the server and without leaving the game, enter an empty server without mods
4.Watch a person fall through the texture, which in theory should be standard when leaving that server

**Expected behaviour**
To prevent this from happening, the player needs to re-enter the MTA, but on my server people abuse it and kill it from under the texture

**Version**
MTA 1.5.8

**Comment by stoneage-mta** [comment]
afaik this bug was fixed in #1930, can you please test with latest nightly build?

**Comment by PlatinMTA** [comment]
> afaik this bug was fixed in #1930, can you please test with latest nightly build?

I just tested with r20762, that bug is NOT fixed. It's just been made worse.

Since a few days, I have been getting a lot of reports regarding this issue. My community has various servers, some with custom street models and some without. Since the release build being pushed to r20762 this issues about falling thought the ground on zones where the custom streets are had increased by a lot.

Sadly, that fix didn't work from the first place it seems.

**Comment by ccw808** [comment]
Does the bug appear in r20698? If not please find out which version the bug started

**Comment by PlatinMTA** [comment]
I am pretty sure it started in r20762 last week, because the auto-default update is the r20762 since then and we had been getting reports about this from around the same time.

~~I'll test in a minute, brb.~~ ~~(one hour later...)~~

**r20769** does have the bug
**r20762** does have the bug (double tested it)
**r20761** does not have the bug
**r20729** can't test it, my game crashes when trying to connect to the second server
**r20723** can't test it, same crash
**r20718** can't test it, same crash
**r20698** does not have the bug

I don't think that we need to test more versions. The bug appeared on #1818 (#1930). Although it would really nice if it worked, something is wrong in that pull request.

Is important to note that the versions that "have" the bug are just versions that have it every time. Before, this bug occurred but not often enough (i don't even know if there was a reliable way to reproduce it). Sometimes some objects would lack the collisions, but it was rare.

**Comment by PlatinMTA** [comment]
Just for the record, **r20775** still has this issue.

**Comment by ccw808** [comment]
Please test r20778

**Comment by PlatinMTA** [comment]
> Please test r20778

It's fixed. I do not fall through the ground anymore. Thank you.

**Comment by AndreyFant** [comment]
It's fixed. Thank you.
