### ISSUE TITLE
fetchRemote is broken on latest nightly

### ISSUE THREAD

**Issue by theSarrum** [multitheftauto/mtasa-blue#2261]
**Describe the bug**
`fetchRemote` is broken on the client side in the latest nightly version and causes the game to crash.

**To reproduce**
Steps to reproduce:
1. Start runcode
2. `crun fetchRemote ( "https://mtasa.com", { }, function ( ... ) iprint ( ... ) end )`

**Version**
r20879

**Additional context**
```
Version = 1.5.8-release-20879.0.000
Time = Tue Jun 15 22:04:17 2021
Module = D:\Program Files (x86)\MTA San Andreas 1.5\MTA\libcef.dll
Code = 0xC0000005
Offset = 0x02436FF1

EAX=00000003  EBX=00000000  ECX=61C4B958  EDX=1F820C37  ESI=00000000
EDI=61C4B958  EBP=2652F8D8  ESP=2652F8BC  EIP=5D1C6FF1  FLG=00010202
CS=0023   DS=002B  SS=002B  ES=002B   FS=0053  GS=002B
```

[crashdump r20879.zip_](https://upload.mtasa.com/u/151768468/crashdump%20r20879.zip_)

**Comment by Dutchman101** [comment]
I can't reproduce a crash

Results:
![rc](https://user-images.githubusercontent.com/12105539/122116776-4e241a00-ce26-11eb-8b3a-2b8221fee8ee.png)

**Comment by StrixG** [comment]
Can confirm the crash in r20879.
```
Version = 1.5.8-release-20879.0.000
Time = Tue Jun 15 22:13:42 2021
Module = E:\Games\MTA San Andreas 1.5\MTA\libcef.dll
Code = 0xC0000005
Offset = 0x02436FF1

EAX=00000003  EBX=00000000  ECX=9329B958  EDX=AB812567  ESI=00000000
EDI=9329B958  EBP=2D40F8D8  ESP=2D40F8BC  EIP=8E816FF1  FLG=00010282
CS=0023   DS=002B  SS=002B  ES=002B   FS=0053  GS=002B
```
[Dump](https://upload.mtasa.com/u/717605284/client_1.5.8-release-20879.0.000_libcef_02436ff1_5_EGMb_0138A8C0_55F3_00D_28BFE_20210615_2213.dmp_)

**Comment by xLive** [comment]
I can reproduce it too

also, for some reason I can reproduce the same crash offset with [DGS](https://wiki.multitheftauto.com/wiki/Resource:Dgs), but it doesn't use `fetchRemote` in the client-side

**Comment by AlexTMjugador** [comment]
The crash occurs on `libcef.dll`, which is a CEF library, not related to the `fetchRemote` implementation whatsoever. Therefore, I think it's unlikely that the crash is caused by `fetchRemote`. Is a CEF instance running when the crash happens?

**Comment by patrikjuvonen** [comment]
I think the only thing in common with CEF and fetchRemote is the fact both use address white/blacklisting via settings menu.

FetchRemote uses netcode, but this doesn't directly point to it.

**Comment by Dutchman101** [comment]
Dumptrace:

```
CONTEXT:  (.ecxr)
eax=00000003 ebx=00000000 ecx=61c4b958 edx=1f820c37 esi=00000000 edi=61c4b958
eip=5d1c6ff1 esp=2652f8bc ebp=2652f8d8 iopl=0         nv up ei pl nz na po nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010202
libcef!absl::variant_internal::VariantCoreAccess::CheckedAccess [inlined in libcef!base::DictionaryValue::HasKey+0x21]:
5d1c6ff1 837e1006        cmp     dword ptr [esi+10h],6 ds:002b:00000010=????????
Resetting default scope

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 5d1c6ff1 (libcef!absl::variant_internal::VariantCoreAccess::CheckedAccess)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 00000000
   Parameter[1]: 00000010
Attempt to read from address 00000010

PROCESS_NAME:  gta_sa.exe

READ_ADDRESS:  00000010 

ERROR_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.

EXCEPTION_CODE_STR:  c0000005

EXCEPTION_PARAMETER1:  00000000

EXCEPTION_PARAMETER2:  00000010

STACK_TEXT:  
2652f8d8 5d299a2d     61c4b958 00000003 280714c0 libcef!base::DictionaryValue::HasKey+0x21
2652f960 5d299818     2652f9c8 2652fac4 00000005 libcef!extensions::Extension::Create+0x1ef
2652f9a0 5f26b0ec     2652f9c8 2652fac4 00000005 libcef!extensions::Extension::Create+0x44
2652fa9c 5f26a9af     2652fac0 00000000 00000000 libcef!extensions::CefExtensionSystem::LoadExtension+0x58
2652faec 5f26a8fd     00000000 2652fb18 00000001 libcef!extensions::CefExtensionSystem::LoadExtension+0x83
2652fb34 5e5db4df     258da1c0 2592cc40 018da20c libcef!extensions::CefExtensionSystem::Init+0x61
2652fb74 5f250eaa     2652fba0 1f820f7f 2652fba0 libcef!AlloyBrowserContext::Initialize+0x24f
2652fb90 5d12a964     258b9328 2802bfc0 2652fbc4 libcef!AlloyMainDelegate::CreateNewBrowserContext+0x3a
2652fbe0 5d12a6d6     ffffff01 615a8744 00000038 libcef!CefRequestContextImpl::Initialize+0x164
2652fc48 6046e501     2652fc58 2652fc5c 258b9318 libcef!CefRequestContextImpl::CreateGlobalRequestContext+0x8a
2652fcb8 5b9d8381     2588a6a0 25801440 00000000 libcef!AlloyBrowserMainParts::PreMainMessageLoopRun+0x171
2652fd0c 5bcfd319     2588a688 2588a688 2652fd2c libcef!content::BrowserMainLoop::PreMainMessageLoopRun+0x41
2652fd30 5b9d7f53     00000000 ffffffff ffffffff libcef!content::StartupTaskRunner::RunAllTasksNow+0x2d
2652fd70 5b9da5c8     2652fdb8 000003e8 00000000 libcef!content::BrowserMainLoop::CreateStartupTasks+0x1c7
2652fdf0 5daa2c31     2652febc 00000000 1f820aff libcef!content::BrowserMainRunnerImpl::Initialize+0x78
2652fe10 5daa2b77     2652febc 2652fe80 1f820adf libcef!CefUIThread::InitializeBrowserRunner+0x59
2652fe30 5f250d45     2652febc 2652fe68 5d0f45cd libcef!CefMainRunner::RunMainProcess+0x27
2652fe3c 5d0f45cd     2652fe4c 2652febc 6155f200 libcef!AlloyMainDelegate::RunProcess+0x25
2652fe68 5d0f4ff1     2652febc 258e8000 626f04d0 libcef!content::RunBrowserProcessMain+0x49
2652fea4 5d0f4cd2     2652febc 00000000 2586c208 libcef!content::ContentMainRunnerImpl::RunBrowser+0x2f5
2652feec 5d0f4293     00000000 768a0000 00000000 libcef!content::ContentMainRunnerImpl::Run+0x122
2652ff14 5daa30c8     258880a8 258642a0 2586c398 libcef!content::ContentMainRun+0x27
2652ff28 5daa2fa4     258557e0 258557e0 0000000b libcef!base::internal::Invoker<base::internal::BindState<`lambda at ../../cef/libcef/browser/main_runner.cc:398:13',base::internal::UnretainedWrapper<CefMainRunner>,base::internal::UnretainedWrapper<base::WaitableEvent> >,void ()>::RunOnce+0x18
2652ff50 5d1dd51a     2586c398 00000e0c 1f820b9f libcef!CefUIThread::ThreadMain+0x84
2652ff70 75f5fa29     25884160 75f5fa10 2652ffdc libcef!base::`anonymous namespace'::ThreadFunc+0xba
2652ff80 76ef7a9e     25884160 00eea1fc 00000000 kernel32!BaseThreadInitThunk+0x19
2652ffdc 76ef7a6e     ffffffff 76f18a48 00000000 ntdll!__RtlUserThreadStart+0x2f
2652ffec 00000000     5d1dd460 25884160 00000000 ntdll!_RtlUserThreadStart+0x1b


FAULTING_SOURCE_LINE:  Y:\work\CEF3_git\chromium\src\base\values.cc

FAULTING_SOURCE_LINE_NUMBER:  1093

SYMBOL_NAME:  libcef!base::DictionaryValue::HasKey+21

MODULE_NAME: libcef

IMAGE_NAME:  libcef.dll

FAILURE_BUCKET_ID:  NULL_CLASS_PTR_READ_c0000005_libcef.dll!base::DictionaryValue::HasKey

OS_VERSION:  10.0.19041.1

IMAGE_VERSION:  91.1.12.0

```

Can a dev please help to investigate it further.. after updating CEF (PR #2259) there was a need (a93fe22 and 3f93481) to follow a .pak files deprecation from [https://bitbucket.org/chromiumembedded/cef/commits/8424f166ccef](https://bitbucket.org/chromiumembedded/cef/commits/8424f166ccef) and I think this crash has something to do with it for the following reasons:

* Alloy runtime is referred in stacktrace
* Extensions are referred in stacktrace

I speculate it further may have something to do with:
* For some reason MTA had already disabled `cef_extensions.pak` as commented in a93fe22 like this: 
`# Below file was included in the deprecation referenced above, but already disabled in MTA beforehand`
`#File "${FILES_ROOT}\mta\CEF\cef_extensions.pak`

So maybe something custom we did (for whatever reason, I didn't look for the commit which disabled it in MTA) now conflicts with what CEF changed (as `cef_extensions.pak` is listed as 1 of the runtimes being merged into the Chrome runtime, just like the other .pak files which were disabled after the CEF update PR got merged)

Otherwise, can someone spot a mistake in how the deprecation was reflected in MTA (those 2 post-PR commits)?

I couldn't even reproduce this crash when testing CEF stability, and haven't gotten it in gameplay (on CEF and fetchRemote-enabled servers) either. Maybe it's really just random, including that its a coincidence to happen while doing things like fetchRemote or "using DGS" as xLive said happened for him. I also don't see any hints to fetchRemote in the stacktrace.

After all, it can also simply be a new bug in CEF. If we can't figure it out soon, we'll have to revert & post it on their bugtracker.

**Comment by patrikjuvonen** [comment]
Hi @Jusonex, do you have any clue what this could be about?

**Comment by theSarrum** [comment]
I think I've figured out what the issue is. When updating the client via the menu, there are no new CEF-specific pak files (chrome_100_percent.pak, chrome_200_percent.pak, resources.pak). However, if you download the build manually from the nightly build server, then these files are there and this crash does not occur. We need a similar solution as we did for Unifont.

**Comment by botder** [comment]
~~@Dutchman101 if what @theSarrum wrote is true, then the "unifont" problem happened again, like I told you in a private conversation.~~

Edit: Ingame update updates to `Multi Theft Auto v1.5.8-release-20870`, which doesn't include the recent CEF version update.

**Comment by Dutchman101** [comment]
> Edit: Ingame update updates to `Multi Theft Auto v1.5.8-release-20870`, which doesn't include the recent CEF version update.

The nightly update channel was rolled back (due to this issue), but it was sending r20879 for about a day before that. So it's still relevant.

Anyways, i expected that Premake would fetch and include the .pak files

**Comment by Dutchman101** [comment]
> Edit: Ingame update updates to `Multi Theft Auto v1.5.8-release-20870`, which doesn't include the recent CEF version update.

The nightly update channel was rolled back (due to this issue), but it was sending r20879 for about a day before that. So it's still relevant.

Anyways, so that's probably true - it explains why users on the nightly auto updater channel could reproduce, but for instance I couldn't (since i updated MTA using the full installer from nightly page).

Are we going to add these .pak files to nightly channel distibutions now? @ccw808 
We may have a dilemma here - i wonder about the impact to auto-updater package size. But since this is a change in CEF we cannot bypass, we _need to follow_ in order to ever keep CEF up-to-date within MTA again.

**Comment by ccw808** [comment]
Problem is build server has a list of CEF files which is not in sync with reality

It did have:
```
MTA\icudtl.dat
MTA\CEF\cef.pak
MTA\CEF\cef_100_percent.pak
MTA\CEF\cef_200_percent.pak
MTA\CEF\devtools_resources.pak
MTA\CEF\locales\en-US.pak
MTA\natives_blob.bin
MTA\snapshot_blob.bin
MTA\v8_context_snapshot.bin
MTA\libcef.dll
MTA\libEGL.dll
MTA\libGLESv2.dll
```

I've changed that to:
```
MTA\icudtl.dat
MTA\CEF\chrome_100_percent.pak
MTA\CEF\chrome_200_percent.pak
MTA\CEF\resources.pak
MTA\CEF\locales\en-US.pak
MTA\snapshot_blob.bin
MTA\v8_context_snapshot.bin
MTA\libcef.dll
MTA\libEGL.dll
MTA\libGLESv2.dll
```

Hopefully that should fix it

**Comment by Dutchman101** [comment]
> Hopefully that should fix it

I confirmed it's fixed by going to r20845 (using full installer), setting my build channel to `nightly` and bumping nightly channel for the test, so I received the auto-update. Then, no crash or issue happened, I also tried the repro.

Nightly channel remains bumped to `r20880` because the issue has been fixed ; )

**Comment by Dutchman101** [comment]
This is weird, the problem is not solved, even despite my testing results some users are still getting the same crash (libcef.dll @ 0x02436ff1) and some user on Discord also asked for help after he started crashing (he's a nightly channel user). Rolling it back again and taking the builds out of roulation.

cc @ccw808 that it's not fixed yet

**Comment by ccw808** [comment]
Did you test using a new install directory?

**Comment by Dutchman101** [comment]
> Did you test using a new install directory?

No, i downgraded my existing installation to `r20845` (in the same folder) using full installer and then waited for the nightly channel updater (my test) to arrive and overwrite it.

If you needed more than just know the answer, I'll soon perform 2 tests with a different folder (of which 1 is installing `r20845` in a new folder and getting it overwritten by nightly channel again, and 1 is just running the latest nightly from full installer without auto-updater being involved - where like before, we surely can't reproduce as it's not the scenario of this issue)

Still i don't know why I couldn't reproduce it before assuming fixed, but in the end crash stats quickly revealed (and that user on nightly channel asking for help shortly after bumping the nightly updater) that it wasn't fixed by the steps you took to update CEF files.

**Comment by Dutchman101** [comment]
Nvm, i made a mistake of thought. I personally couldn't reproduce (in my last test) because i had very recent nightly builds installed from full installer, which placed the new runtime files (chrome_100 and 200) in my MTA installation folder.

So when i downgraded and upgraded again through nightly channel.. i didn't crash because the required files after all were still _present_ (downgrade doesn't uninstall them)

Bottom line, the original issue is unchanged.. updating files on the build server had no effect and nightly channel users keep crashing as soon we bump nightly revision (if they come from an earlier build and haven't ever used the full installer of any post-CEF update build.

You probably just missed something while updating the served files @ccw808

Anyways the impact is fairly low: it affects only nightly channel users after receiving lightweight update, and will affect no one for now as we're not going to bump nightly updater channel until fixed.

**Comment by ccw808** [comment]
Latest build should fix it

**Comment by Dutchman101** [comment]
> Latest build should fix it

Yeah, confirmed to be fixed in r20881
