### ISSUE TITLE
Interface rounded with SVG bug/problem ?

### ISSUE THREAD

**Issue by vkhypado-dev** [multitheftauto/mtasa-blue#4011]
### Describe the bug

Hello, after the SVG update, the round interface's are no longer working, I have already removed `dxSetBlendMode`, I have tried to change the SVG code, color and everything else, but without results, here are the attachments of how it looks with the life below 100, if the life is at 100 and restart the system, it has wonderful quality, but if it is lower than 100, it has horrible quality, and no updates.

With 100 of life.
![Image](https://github.com/user-attachments/assets/6051704f-dece-4bc9-999f-66931b2c9bb2)

With 50 of life.
![Image](https://github.com/user-attachments/assets/508b7f23-45ff-4d1e-a882-da21bd769c81)

```lua
function createComponents(index, x, y, size, animation)
    local config = getConfig()
    if not (index or x or y or size) then
        return false;
    end
    
    local radius = (size / 2) - (2.64 / 2)
    local perimeter = 2 * math.pi * radius    

    if not (elements.components[index]) then
        local svg = svgCreate(size, size, string.format([[
            <svg width="%s" height="%s" viewBox="0 0 %s %s" fill="none" xmlns="http://www.w3.org/2000/svg">
                <circle 
                    cx="%s" cy="%s" r="%s" stroke="%s" stroke-width="2.64" 
                    stroke-dasharray='%s' stroke-dashoffset='0' 
                    stroke-linecap='round'
                />
            </svg>
        ]], size, size, size, size, size/2, size/2, radius, '#FFFFFF', perimeter));

        local xml = svgGetDocumentXML(svg)

        elements.components[index] = {
            svg = svg,
            radiusLenght = perimeter,
            xml = xml,
            rect = xmlFindChild(xml, 'circle', 0),

            offset = {
                value = 100,
                state = false,
            }
        }
    else
        local data = elements.components[index]
        local value = math.floor(config.components[index].Func(localPlayer))

        if data.offset.value ~= value then
            if not data.offset.state then
                data.offset.state = true
            end

            elements.components[index].offset.value = lerp(elements.components[index].offset.value, value, 0.1)

            xmlNodeSetAttribute(data.rect, 'stroke-dashoffset', perimeter * (1 - (elements.components[index].offset.value / 100)))
            svgSetDocumentXML(data.svg, data.xml)
        elseif data.offset.state then
            data.offset.state = false
        end

        dxDrawImage(x, y, size, size, elements.components[index].svg, 0, 0, 0, rgba(config.components[index].Color[1], config.components[index].Color[2], config.components[index].Color[3], 1, animation))

        if (config.components[index].Icon) then
            local centerX, centerY = x + (size / 2) - respc(32 / 2), y + (size / 2) - respc(32 / 2)
            dxDrawImage(centerX, centerY, respc(32), respc(32), config.components[index].Icon, 0, 0, 0, rgba(255, 255, 255, 1, animation))
        end
    end
end
```

in the top, is my code.

### Steps to reproduce

Update MTA to the latest version

### Version

Client: 1.6.0-9.22942.0

### Additional context

I hope we can resolve it, as I believe that 90% of MTA BR servers use even 0.1%

Not to mention the foreign servers.

### Relevant log output

```shell

```

### Security Policy

- [x] I have read and understood the Security Policy and this issue is not security related.

**Comment by fuchles** [comment]
Totally the same sitatuin with radialbars, but it was working just yesterday. Hope, we will get back to the older version.

https://youtu.be/qAhed6pINQk

**Comment by vkhypado-dev** [comment]
Yes! I hope Dutchman sees the mess they made on SVG. I believe they shouldn't have changed it, as they just created several problems in the BR community, and in other countries. He thinks that only BR's use SVG, but there are plenty of servers that use it. @Dutchman101 I hope you fix this bug!

**Comment by Lpsd** [comment]
Dutchman is not the developer of this change in functionality. Please only comment when you have something valuable to add.

You've also closed the issue by mistake.

**Comment by Lpsd** [comment]
Please provide a minimal (basic) reproduction script which doesn't rely on functions, variables or assets which are not included in your code. This resource should ideally be zipped up, so it can be extracted directly into the resources folder and tested, without any messing around.

Thank you

**Comment by Lpsd** [comment]
Please stop closing the issue. Access _can_ be restricted from GitHub.

Or are you saying the issue is resolved now? If so, please explicitly confirm that along with how you resolved it.

**Comment by vkhypado-dev** [comment]
> Please stop closing the issue. Access _can_ be restricted from GitHub.

But this is practically a script that can be extracted and placed normally, as everything is in the utils, anyway, I clicked wrong, I still don't know much about the insues on github.

Ah, for the record, Dutchman approved the SVG code change.

**Comment by Lpsd** [comment]
so `getConfig` is a function in MTA? What about `respc`? And how about the `elements` table?

I don't say things for the fun of saying them. Please provide a standalone reproduction resource which can be used directly without any messing around. The script you've provided would require time to implement these missing functions and variables, which I am personally not interested in doing.

Thank you

**Comment by vkhypado-dev** [comment]
```lua
local config = {
    components = {
        {
            Title = 'Health',

            Color = {233, 71, 71},
            Icon = 'health',
            Func = function()
                return getElementHealth(localPlayer);
            end
        };
        {
            Title = 'Armor',

            Color = {2, 196, 202},
            Icon = 'armor',
            Func = function()
                return getPedArmor(localPlayer);
            end
        };        {
            Title = 'Food',

            Color = {229, 124, 64},
            Icon = 'food',
            Func = function()
                return (getElementData(localPlayer, 'food') or 50);
            end
        };
        {
            Title = 'Thirst',

            Color = {93, 178, 242},
            Icon = 'thirst',
            Func = function()
                return (getElementData(localPlayer, 'sede') or 50);
            end
        };
    };
};

function lerp (a, b, t)
    return a + (b - a) * t;
end

function createComponents(index, x, y, size)
    if not (index or x or y or size) then
        return false;
    end
    
    local radius = (size / 2) - (2.64 / 2)
    local perimeter = 2 * math.pi * radius    

    if not (elements.components[index]) then
        local svg = svgCreate(size, size, string.format([[
            <svg width="%s" height="%s" viewBox="0 0 %s %s" fill="none" xmlns="http://www.w3.org/2000/svg">
                <circle 
                    cx="%s" cy="%s" r="%s" stroke="%s" stroke-width="2.64" 
                    stroke-dasharray='%s' stroke-dashoffset='0' 
                    stroke-linecap='round'
                />
            </svg>
        ]], size, size, size, size, size/2, size/2, radius, '#FFFFFF', perimeter));

        local xml = svgGetDocumentXML(svg)

        elements.components[index] = {
            svg = svg,
            radiusLenght = perimeter,
            xml = xml,
            rect = xmlFindChild(xml, 'circle', 0),

            offset = {
                value = 100,
                state = false,
            }
        }
    else
        local data = elements.components[index]
        local value = math.floor(config.components[index].Func(localPlayer))

        if data.offset.value ~= value then
            if not data.offset.state then
                data.offset.state = true
            end

            elements.components[index].offset.value = lerp(elements.components[index].offset.value, value, 0.1)

            xmlNodeSetAttribute(data.rect, 'stroke-dashoffset', perimeter * (1 - (elements.components[index].offset.value / 100)))
            svgSetDocumentXML(data.svg, data.xml)
        elseif data.offset.state then
            data.offset.state = false
        end

        dxDrawImage(x, y, size, size, elements.components[index].svg, 0, 0, 0, tocolor(config.components[index].Color[1], config.components[index].Color[2], config.components[index].Color[3], 255))
    end
end

```

Done.

**Comment by Lpsd** [comment]
Still missing variables definition (where is `elements.components` definition?)

Also, GitHub uses three backticks followed by a language identifier, see https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

The reason I asked you to package this up into a zip (including the meta.xml and Lua scripts; as you would for any other resource), instead of just posting random bits of code here, is so that you can verify the resource works as standalone. This clearly will not work as it stands, I know this without even having to test it.

If you want us to spend effort resolving the issue, then make the initial effort to give us a proper reproduction resource.

**Comment by Lpsd** [comment]
Anyway, it seems like @TheNormalnij found a solution for the issue. If you can provide what we asked for, great - otherwise it doesn't matter as the fix will be pushed soon, and you can test it yourself.

Thanks for the report nonetheless.

**Comment by vkhypado-dev** [comment]
> Still missing variables definition (where is `elements.components` definition?)
> 
> Also, GitHub uses three backticks followed by a language identifier, see https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks
> 
> The reason I asked you to package this up into a zip (including the meta.xml and Lua scripts; as you would for any other resource), instead of just posting random bits of code here, is so that you can verify the resource works as standalone. This clearly will not work as it stands, I know this without even having to test it.
> 
> If you want us to spend effort resolving the issue, then make the initial effort to give us a proper reproduction resource.


Only define `elements = { components = {} }`

**Comment by vkhypado-dev** [comment]
> Anyway, it seems like @TheNormalnij found a solution for the issue. If you can provide what we asked for, great - otherwise it doesn't matter as the fix will be pushed soon, and you can test it yourself.
> 
> Thanks for the report nonetheless. 

Okay, I'll send the .zip in a little while because I'm not on the PC...

**Comment by vkhypado-dev** [comment]
> Anyway, it seems like @TheNormalnij found a solution for the issue. If you can provide what we asked for, great - otherwise it doesn't matter as the fix will be pushed soon, and you can test it yourself.
> 
> Thanks for the report nonetheless. 

Okay, I'll send the .zip in a little while because I'm not on the PC...
