### ISSUE TITLE
Weird camera movement in the map editor

### ISSUE THREAD

**Issue by NoType1** [multitheftauto/mtasa-blue#763]
**Describe the bug**
The freecam has very weird and snappy movement. So if you try to move your camera, it feels as if it is being snapped into place instead of moving smoothly (like it used to be)

**To reproduce**

Steps to reproduce the behaviour:
1. Go to local map editor (it can be in a server as well)
2. Move camera around when its in the freecam mode

**Expected behaviour**
A properly functioning freecam with no snappy movement. (I'm reporting this on the behalf of lots of other mappers, including myself) 
The bug does not occur when you press F for the cursor mode. 

**Version**
MTA 1.5.6 Latest build.
OS: Windows 10, 8.1 and 7

**Additional context**
I hope that someone can find a fix for this. It is very frustrating, and totally demotivating.
This has all started after the latest update.

**Comment by NoType1** [comment]
Here's a screenshot of my settings 
![image](https://user-images.githubusercontent.com/923242/49341932-eaf98000-f64b-11e8-893b-4cbf26c273c9.png)

**Comment by Wolfee-J** [comment]
Set FPS limit to 60, at-least for me 30 FPS has been slower then normal with the latest updates.

**Comment by Wolfee-J** [comment]
I believe this - https://github.com/multitheftauto/mtasa-blue/issues/643#issuecomment-443262422 is related.

**Comment by MegadreamsBE** [comment]
Proper interpolation could smooth things out then (consistent timing between moving between two camera positions).

**Comment by Wolfee-J** [comment]
I'm creating a new freecam system at the moment. However the screen tearing
is still related because it makes the issue stand out a whole lot more then
it initially would have.

**Comment by qaisjp** [comment]
@Deltanic has narrowed it down to r14746. r14744 works fine for him.

https://buildinfo.mtasa.com/?SHA=&Author=&Branch=&Revision=14746

So this is likely caused by bc940094f0d910eea90319260644adecc6292b3c (cc @ccw808)

**Comment by KnOwNmta** [comment]
Hello,
Please, It would be kind of you to look after the problem and get it solved as soon as possible. I'm managing a Discord Community for mappers in Multi Theft Auto and a lot of people, if not everyone is struggling and pissed off. We all have projects to finish but unfortunately, we can't bear with the current state of the editor. We appreciate your work!

**Comment by zatley** [comment]
Please fix, I can't finish my feat with Vortex right now!!

**Comment by qaisjp** [comment]
OK, **in 6 or 7 hours** try the latest nightly.

If you do not have a nightly build:

1. Start MTA
1. Click Settings
1. Click on the Advanced tab
1. Update your build type in the "Auto updater" section

Please report back and tell us if this fixes your problem. Also please tell us your graphics configuration.

**Comment by NoType1** [comment]
Thank you very much for trying to resolve this issue

**Comment by qaisjp** [comment]
Okay, @NoType1 @zatley @KnOwNmta please tell us:

- If the latest nightly update solves the issue for you
- What is your graphics card?

If the auto-updater doesn't work after following the instructions here: https://github.com/multitheftauto/mtasa-blue/issues/763#issuecomment-452858308, you can [click here instead](https://nightly.mtasa.com/mtasa-1.5.6-rc-16262-20190110.exe).

**Comment by 1thwonder** [comment]
Latest nightly update didn't fix it for me.
GPU: GTX 970

**Comment by ccw808** [comment]
Please confirm which version you tested with by pressing F8 and entering the command: **ver**

**Comment by botder** [comment]
Please also try the test branch with a solution without the reverted commits. You can get the build here: [MTA:SA Test Builds](https://nightlytest.mtasa.com/) under **feature/test-message-loop**.

Download link for the Windows MTA:SA client: https://nightlytest.mtasa.com/download?type=windows32&branch=feature%2Ftest-message-loop&hash=a4a09aed0880d1e923c945c93e579e5626aeda21

**Note:** Test builds do not include the default resource package, you have to copy these.

**Comment by 1thwonder** [comment]
I tested v1.5.6-release-16256.

**Comment by 1thwonder** [comment]
Test Branch build fixed it for me. (Multi Theft Auto v1.5.6-custom)

**Comment by NoType1** [comment]
Tested v1.5.6-release-16256 with a GTX1050Ti, that did not fix the problem for me either

**Comment by botder** [comment]
@NoType1 Please test the test branch build above.

**Comment by NoType1** [comment]
@botder the test branch build fixed it for me as well! :)

**Comment by KnOwNmta** [comment]
@botder The test branch build fixed it for me. The latest nightly didn't @qaisjp

GPU: NVIDIA GeForce GTX 1060

**Comment by StifflersMom** [comment]
@botder The test build fixed it for me, too.

Multi Theft Auto v1.5.6-release-16262 moves much smoother, setting fps to 25 in map editor does not freeze the movement.

Multi Theft Auto v1.5.6-release-16257 moves totally laggy, setting fps to 25 in map editor freezes the movement mostly for some seconds, sometimes for more than 10 sec.

GPU: Nvidia GTX 660

edit: I checked the 16262 against the test build more times now, the 16262 moves good but the test build moves perfect. Also there are no movement dropsin map editor if I set fps to 25 with the test build.
If i set fps to 25 with 16262, there are drops in movement in map editor.

**Comment by ccw808** [comment]
@1thwonder
@NoType1 Please test with https://nightly.mtasa.com/mtasa-1.5.6-rc-16262-20190110.exe

**Comment by 1thwonder** [comment]
Multi Theft Auto v1.5.6-release-16262 seems to be working fine, I think you've solved it.

**Comment by NoType1** [comment]
@ccw808 Yes! It works. It feels very smooth again. Thank you very much :)

**Comment by ccw808** [comment]
As the test branch has slightly better results according to StifflersMom, I think we should revert 61fccbc (Revert "Refactored frame rate limiter") and merge a4a09ae (Add extra message loop in idle handler)

**Comment by qaisjp** [comment]
Sounds good to me. @botder if you're happy with that please go ahead :slightly_smiling_face: :tada:

**Comment by Wolfee-J** [comment]
Can someone test to see if https://github.com/multitheftauto/mtasa-blue/issues/643 has been fixed? Sounds like this could very likely have been related.

**Comment by TemaSM** [comment]
@CodyJL I'm testing it right now, will provide more info soon.

**Comment by TemaSM** [comment]
@CodyJL I finished testing (will attach dxdiag report to corresponding issue). Problem still occurs 😢

**Comment by patrikjuvonen** [comment]
These fixes were never supposed to fix screen tearing and any discussion should be moved to the corresponding issue at #643. Locking this issue.
